export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_FULFILLED = 'FETCH_SEARCH_RESULTS_FULFILLED';
export const FETCH_SEARCH_RESULTS_FAILED = 'FETCH_SEARCH_RESULTS_FAILED';
export const SET_DETAIL_ITEM = 'SET_DETAIL_ITEM';
